import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [typedWord, setTypedWord] = useState("");
  const [results, setResults] = useState([]);
  const handleChange = async (e: React.ChangeEvent<HTMLInputElement>) => {

    setTypedWord(e.target.value);
    const results =
      e.target.value !== ""
        ? await fetch("/api/autocomplete?word=" + e.target.value).then((res) =>
            res.json()
          )
        : [];
    console.log(results);
    setResults(results);
  };

  const handleWordClick = (result: string) => {
    console.log("user clicked: " + result);
    setTypedWord(result)
  };
  return (
    <>
      <Head>
        <title>Vercel Interview</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center">
        <div className="flex items-center gap-2">
          <input
            className="w-80 rounded-md p-2 text-black"
            type="text"
            onChange={handleChange}
            value={typedWord}
          />
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="h-8 w-8"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
            />
          </svg>
        </div>
        <div className="mt-5 flex flex-col gap-5">
          {results.map((result, index) => (
            <button
              className="rounded-sm bg-zinc-600 p-2"
              key={index}
              onClick={() => handleWordClick(result)}
            >
              {result}
            </button>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
